name: librenotes

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+10
  provider: ^3.1.0+1
  share: ^0.6.3+1
  shared_preferences: ^0.5.4+5
  sqflite: ^1.1.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
